name: ciphercopy_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  crypto: ^3.0.6
  ansicolor: ^2.0.1
  args: ^2.4.2
  logger: ^2.0.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
